### ISSUE TITLE
GPS navigates to single folder when renaming the folder (was All GPS coordinates disappear)

### ISSUE THREAD

**Issue by JamesMortimer** [StarCpt/SE-GpsFolders#2] opened 2023-11-01 19:57 UTC
ok, this is a weird one.

WHEN I am in the GPS editor
AND I have ALL GPS coordinates organized into 4 folders
AND I create a new GPS from my current location
AND I attempt to rename the GPS item right away (e.g. "Platform")
AND I try to add it to a folder name right away to that new GPS entry, without exiting the GPS editor (e.g. "Near Mars")
THEN when I do exit the editor and return,  I see none of my GPS coordinates
AND I see only the single new entry as the top item called "Platform", no other items
AND it appears as a folder, not a regular entry
AND it cannot be opened and contains no GPS items
AND my GPS export to clipboard is empty
AND if I load a backup from 5, 10, 15 or 20 minutes ago, they also do not have any GPS entries other than this new one (which strangely, I did not have 5 minutes ago)
BUT if I completely exit the game and restart, then load the last saved game (current version or 20 minute backup)
THEN everything is back as it should be before I tried to add the new GPS entry

HOWEVER if instead
WHEN I am in the GPS editor
AND I have ALL GPS coordinates organized into 4 folders
AND I create a new GPS from my current location
AND I make sure to exist the GPS editor and re-enter the editor
AND then I add it to a folder name
THEN everything works as expected.

ALSO
if I create a GPS item from current location, and give it a folder name of ;'test' or 'test2', then ESC out of the GPS menu, then come back, the new item has no folder. but if I switch to the comms view then exit then come back, it is in a folder, or if I exit then come back and add the name, it works fine. Same effect even if I click ENTER in the folder text box (which seems to do nothing) or If I first click on the 'description' field, to exit the text entry dialog, before pressing ESC to exit the GPS editor screen.

ALSO
if I create a GPS item from current location, exit, come back, give it folder of 'test', exit, come back, create a second GPS item from current location, it pops up with the folder ALREADY set as test.

some of this I can't seem to reproduce, but what happens consistently is creating a GPS from current, adding a tag, exit and come back, the tag is BLANK. adding it again, exit and come back, it's there. So something is certainly weird with newly created GPS items from current location.

Enjoy!

**Comment by StarCpt** [comment] 2023-11-03 03:21
I'm unable to reproduce any of the issues, do you mind sharing the world and a list of plugins you're using?

**Comment by JamesMortimer** [comment] 2023-11-03 07:15
Further testing. It seems to happen reproducibly when I edit the name of an newly created entry while the game is paused, as follows:

WHEN I open the GPS editor
AND I have about 60 entries sorted into about 5 folders
AND I select one of the GPS entries (probably a folder in this case)
AND I press Pause to pause the game
AND I create a new GPS from the current location
AND I try to rename the GPS coordinates
THEN all of the GPS coordinates disappear except for the first one
AND the first one has the folder icon
AND the first one has the new name I tired to give the new coordinate
AND the problem persists even if I reload the world from the last backup
AND the problem persists even if I exit to the main menu and reload the world
BUT the problem resolves if I exit the game entirely and reload the world (all my coordinates are back, minus the one I tried to create and rename)

**Comment by JamesMortimer** [comment] 2023-11-03 07:16
I have a bunch of mods and plugins. I should try testing it in a vanilla world.

**Comment by JamesMortimer** [comment] 2023-11-03 18:15
I think I got it. I can make it happen in vanilla with a new world if I rename a folder. I could have been going fast and accidentally renamed a folder rather than a GPS waypoint item in my previous tests, by mistake.

Here is what I did:

Check out 'round three' in this attachment for screenshots
[GPS Folder Error Report.pdf](https://github.com/StarCpt/SE-GpsFolders/files/13253370/GPS.Folder.Error.Report.pdf)

1) Removed all plugins and mods from plugin loader

2) Created a new world, all default settings
	Alien Planet 2023-11-03 13-34 Test GPS Folders

3) WHEN I go into the GPS editor  
AND I created 3 GPS coordinates from current location
AND I enter 'test' in the folder fields for two and 'test2' for one of them
THEN they appear as normal, not in folders (Is this as expected because you have to exit and re-enter to update? It’s odd, but maybe a game limitation?)
	
AND WHEN I exit the GPS editor and com back in
THEN they appear in folders
	
AND I can expand the folders as expected

So far so good.

4) WHEN I expand folders
AND I select the first folder
AND I edit the name of the folder to be 'test3'
THEN I see my folders disappear to be replaced with a house icon and ...test3 as the folder name

5) WHEN I exit and re-enter the GPS editor
THEN I see this the strange house folder and waypoint 3 disappeared
AND the test3 folder seems to be empty, despite #1 and #2 being ‘in’ the test3 folder, if I expand the folders or not

6) When I add 3 new waypoints using ‘new from current position’ or ‘new from clipboard’, no additional GPS markers appear.

7) WHEN I SAVE, then EXIT game, thee CONTINUE GAME, the issue persists!!!
	
8) BUT WHEN I EXIT THE APPLICATION ENTIRELY, then re-open and CONTINUE GAME, I see this. Which has the test2 folder, the properly renamed test3 folder, the first 3 bookmarks in the right folders,  and all the missing GPS waypoints I added that did not appear.

**Comment by JamesMortimer** [comment] 2023-11-03 18:18
[Alien Planet 2023-11-03 13-34 Test GPS Folders.zip](https://github.com/StarCpt/SE-GpsFolders/files/13253405/Alien.Planet.2023-11-03.13-34.Test.GPS.Folders.zip)

**Comment by JamesMortimer** [comment] 2023-11-04 04:27
And it just happened again in my game world... all I did was open the GPS manager (which I have organized into folders), add a GPS from current location, then try to rename it. I was careful to make sure I was renaming the new entry, not the folder in this case. All coordinates disappeared and the first entry was a 'house' icon with a '...' and the name I was trying to rename to. Had to fully exit the game and reload. If I create the GPS, then exit and re-enter the GPS manager, then I can rename the new GPS entry without issue.

**Comment by StarCpt** [comment] 2023-11-04 04:29
Try double clicking the entry with the house icon

**Comment by StarCpt** [comment] 2023-11-04 04:33
The house with the dots mean that you're in the folder. You can normally enter the folder view by double clicking it, it seems like changing the folder name puts you in the folder which is not intended.

**Comment by StarCpt** [comment] 2023-11-04 05:13
fixed the bug and a crash I found temporarily in the dev branch, but I'll probably rewrite the whole thing because it's a hodgepodge of patches and temporarily permanent solutions as it stands

**Comment by JamesMortimer** [comment] 2023-11-06 21:06
_"because it's a hodgepodge of patches and temporarily permanent solutions as it stands"_ ... said no developer ... ever...

Thanks for looking at this and fixing the behavior. Strange that it keeps you in the folder view even if you unload and reload the world, but not if you unload and reload the game. The double click thing seems to work in my test...I didn't even realize that was a feature otherwise I would have tried it. I will use it all the time now.

Maybe add a note about 'double click a folder title to navigate into a folder or the home icon to return to the top level' in the usage section of the github page. I see the house there now, and the ..., and it makes sense now, just wasn't something I tried.

**Comment by JamesMortimer** [comment] 2023-11-06 21:14
Confirmed that ones it puts me into 'folder view' when I rename a tag, I can double click the house to get back to the full view.

**Comment by StarCpt** [comment] 2024-05-14 10:34
This should have been fixed in the new update.

**Closed by StarCpt** 2024-05-14 10:34 UTC
